version: "2"
checks:
  return-statements:
    config:
      threshold: 6
plugins:
  gofmt:
    enabled: true
  govet:
    enabled: true

exclude_patterns:
  - "!**/**.go"
  - "**/*_test.go"
  - "resource/resource_list.go"
