linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    # default linter
    # - errcheck # there are to many failures at the moment
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # custom linter
    - gofmt
