version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - noinlineerr
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    staticcheck:
      checks:
        - all
        # Default exclusions
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        # Incorrectly formatted error string: there are a lot of these
        - "-ST1005"
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
