version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    staticcheck:
      checks:
        [
          # Default checks
          "all",
          "-ST1000",
          "-ST1003",
          "-ST1016",
          "-ST1020",
          "-ST1021",
          "-ST1022",
          # Local additions
          "-ST1005",
        ]
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
run:
  go: "1.24"
