ARG GO_VERSION
FROM docker.io/golang:${GO_VERSION}-alpine AS base

ARG GOSS_VERSION=v0.0.0
WORKDIR /build

RUN --mount=target=. \
    CGO_ENABLED=0 go build \
    -trimpath \
    -ldflags "-X github.com/goss-org/goss/util.Version=${GOSS_VERSION} -s -w" \
    -o "/release/goss" \
    ./cmd/goss

FROM alpine:3.24

COPY --from=base /release/* /usr/bin/

RUN mkdir /goss
VOLUME /goss
