port=8053
auth-server=ns1.dnstest.io,eth0
auth-sec-servers=ns2.dnstest.io
auth-zone=dnstest.io
auth-soa=2026051301,hostmaster.dnstest.io,1200,120,604800
host-record=dnstest.io,54.243.154.1
host-record=ip6.dnstest.io,2404:6800:4001:807::200e
host-record=a.dnstest.io,192.30.252.153
mx-host=dnstest.io,a.dnstest.io,5
mx-host=dnstest.io,b.dnstest.io,10
cname=c.dnstest.io,a.dnstest.io
caa-record=dnstest.io,0,issue,comodoca.com
caa-record=dnstest.io,0,issue,letsencrypt.org
caa-record=dnstest.io,0,issuewild,;
txt-record=txt._test.dnstest.io,Hello DNS
srv-host=_https._tcp.dnstest.io,a.dnstest.io,443,0,5
srv-host=_https._tcp.dnstest.io,b.dnstest.io,443,10,10
