FROM debian:bookworm

RUN apt-get -o Acquire::Check-Valid-Until=false update && \
    apt-get install -y apache2 apache2-doc apache2-utils vim-tiny ca-certificates tinyproxy && \
    apt-get remove -y vim-tiny && \
    apt-get clean

RUN update-rc.d apache2 defaults
RUN update-rc.d tinyproxy defaults
RUN mkfifo /pipe
