FROM ubuntu:noble
MAINTAINER Ahmed

RUN apt-get update && \
    apt-get install --no-install-recommends -y apache2=2.4.58-1ubuntu8.1 ca-certificates tinyproxy vim-tiny systemd systemd-sysv && \
    apt-get remove -y vim-tiny && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkfifo /pipe
