name: Integration tests
on:
  # don't build any branch other than master (and prs) when git pushed
  pull_request: {}
  push:
    branches:
      - master
      - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
    paths-ignore:
      - "**/*.md"

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Unit tests and coverage
        run: make cov

  integration-test-linux:
    needs: [lint, coverage]
    name: Integration tests (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Integration tests
        shell: bash
        run: make test-int-all

  integration-test-other:
    needs: [lint, coverage]
    name: Integration tests
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Integration tests
        shell: bash
        run: |
          os_name="$(go env GOOS)"
          make "test-int-${os_name}-all"
